CC      = gcc
CFLAGS  = -Wall -Wextra -O2

SRC     = src
INC     = include

MAIN    = $(wildcard $(SRC)/main.c $(SRC)/principal.c)

SRCS    = $(filter-out $(MAIN), $(wildcard $(SRC)/*.c))

TARGET  = TrabalhoLabProg

all: $(TARGET)

$(TARGET):
	$(CC) $(CFLAGS) $(MAIN) $(SRCS) -I$(INC) -o $(TARGET)

run: all
	./$(TARGET)

clean:
	rm -f $(TARGET)

 
